### ISSUE TITLE
Template rendering and signatures

### ISSUE THREAD

**Issue by FroMage** [mkouba/qute#3]
I think the signature of `CompletionStage<Void> render(Object root, Consumer<String> partsConsumer)` should be `Publisher<String> renderAsync(Object rooot)`, right @cescoffier?

**Comment by FroMage** [comment]
This would incur either a dependency to `org.reactivestreams:reactive-streams:jar:1.0.2` or https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.Publisher.html (if that is supported by Axle @cescoffier?)

**Comment by cescoffier** [comment]
Yes, 
`CompletionStage<Void> render(Object root, Consumer<String> partsConsumer)` should become:
`Publisher<String>` render(Object root)`. 

Yes, it's going to add a dependency on reactive streams until we rebase on Java 9+.

Actually, in term of implementation, we may even consider returning a `Flowable` (implementation of `Publisher` provided in RX Java 2).

**Comment by FroMage** [comment]
I thought we did not want to add RxJava2 dependencies?

**Comment by cescoffier** [comment]
Would be better without, but implementing a `Publisher` is not an easy task.

**Comment by FroMage** [comment]
Well, we can use reactive-streams-operators, no?

**Comment by cescoffier** [comment]
The Smallrye implementation used RX Java 2.

**Comment by mkouba** [comment]
So I will try with `Publisher` first.

**Comment by mkouba** [comment]
Hm, a `Publisher` can serve multiple subscribers and can be called multiple times. In that case, I don't think it's a good match for this `Template` method. 

The idea was to accept a consumer of rendered chunks, something like `Appendable`, and this consumer is invoked whenever a new chunk is available. Once the rendering finished the returned `CompletionStage` is completed. It should be a one-time action. 

Ok, the publisher can reject the subscription attempt - but is it a good practice in the reactive world?

Also, how would you translate/convert the above logic with `CompletionStage` and `Consumer` to a `Publisher`? I've been looking at `org.eclipse.microprofile.reactive.streams.operators.ReactiveStreams` but I haven't found anything relevant, except for `ReactiveStreamsFactory.generate(Supplier<? extends T>)` which however creates an infinite stream...

@cescoffier @FroMage tips and recommendations would be appreciated! :-)

**Comment by mkouba** [comment]
BTW I'm just working on the `Template` API and I'm going to add the `Rendering render()` method where `Rendering` is a construct that encapsulates config , data and "terminal" operations (similar to Stephan's `TemplateInstance` from https://github.com/mkouba/qute/pull/1):

```java
template.render().setData(data).asString();

pullsTemplate.render().consume(exchange.response()::write)
                .whenComplete((v, t) -> {
                    if (t == null) {
                        exchange.ok().end();
                    } else {
                        ...
                    }
                });

template.render().putData("foo", 1).putData("bar", 2).publisher(); // TODO once I know how to implement publisher ;-)
```

**Comment by cescoffier** [comment]
> a Publisher can serve multiple subscribers and can be called multiple times. In that case, I don't think it's a good match for this Template method.

A Publisher can server multiple subscribers, but it's not a must. I would keep it simple an serve only one. Generally, the state is managed at the subscription level. For example, using http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#generate-java.util.concurrent.Callable-io.reactivex.functions.BiConsumer-

However, the consumer (subscriber) should only get the chunk if it requested it (using the `Subscription.request(long)` method).

> CompletionStage is completed. It should be a one-time action.

Should not be an issue to enforce this. Once completed, the subscription is disposed. 

> Ok, the publisher can reject the subscription attempt - but is it a good practice in the reactive world?

Some but not in your case. Just provide a subscription that would allow the consumer to request the chunk and cancel if needed. 

> Also, how would you translate/convert the above logic with CompletionStage and Consumer to a Publisher? I've been looking at 

A `CompletionStage` is eager, meaning than the processing already started when you retrieve the object.
A `CompletionStage` renders everything in one "batch", you only have 1 result or failure.

A (cold) `Publisher` won't start the processing until subscription, even sometimes until the first request. 
A `Publisher` notifies the subscribe of the available `chunks` one by one. 
A `Publisher` waits until the subscriber request chunks before sending them

For your case, we can go through a set of iterations.

First, use an `UnicastProcessor`. Every time you have a chunk call onNext on the processor. It will manage the "request" protocol, and buffer the chunks in the meantime.

**Comment by mkouba** [comment]
Something like this? @cescoffier
```java
UnicastProcessor<String> processor = UnicastProcessor.create();
template.render().consume(s -> processor.onNext(s))
                .whenComplete((v, t) -> {
                    if (t == null) {
                        processor.onComplete();
                    } else {
                        processor.onError(t);
                    }
                });
return processor;
```
But this one caches all the events until a subscriber subscribes if I understand it correctly?

**Comment by cescoffier** [comment]
So if I understand correctly, `consume` is going to call several times (when a chunk is made available) and the CompletionStage that is returned send the error/completion signals. 

If that's right, you would need to make it a bit more "lazy" as follows:

```
return Flowable.defer(() -> {
    UnicastProcessor<String> processor = UnicastProcessor.create();
    template.render().consume(s -> processor.onNext(s))
                .whenComplete((v, t) -> {
                    if (t == null) {
                        processor.onComplete();
                    } else {
                        processor.onError(t);
                    }
                });
         return processor;
});
```

It means that you will only start rendering once one subscriber subscribes. Also, the UnicastProcessor is not shared (every subscription will get its own). 

Do you need to some cleanup if the subscriber cancels the subscription? Typically, we could cancel the future, but not sure what do you in this case.

**Comment by mkouba** [comment]
> So if I understand correctly, consume is going to call several times (when a chunk is made available) and the CompletionStage that is returned send the error/completion signals.

Yes, you do understand it very well.

> Flowable.defer()

I see.

> (every subscription will get its own)

Hm, I'm not sure we want this.

> Do you need to some cleanup...

I don't think so. Rendering a template is usually not a long-running operation.

**Comment by cescoffier** [comment]
> Hm, I'm not sure we want this.

I believe you do. IT means that each subscriber will get its own rendering, and can control it.

**Comment by mkouba** [comment]
> each subscriber will get its own rendering, and can control it.

It should not control it, it should just consume the results. Hmm...

**Comment by cescoffier** [comment]
it somehow controls it using the "request" protocol. You just don't see it as it's hidden behind the `UniCastProcessor`

**Comment by mkouba** [comment]
Ok. I'll try to implement something and then I will politely ask for review ;-). Thanks!

**Comment by mkouba** [comment]
I've created a `PublisherFactory` service provider so that it's pluggable. 

The rxjava impl is here:
https://github.com/mkouba/qute/blob/master/rxjava/src/main/java/com/github/mkouba/qute/rxjava/RxjavaPublisherFactory.java#L14-L27

And the test is here:
https://github.com/mkouba/qute/blob/master/rxjava/src/test/java/com/github/mkouba/qute/rxjava/SimplePublisherTest.java

It seems to work fine. Of course, we can revisit this topic later.

**Comment by cescoffier** [comment]
Looks good to me! We can always revisit later to remove the AsyncPRocessor. But that would require a bit more work and for this use case is not necessary.
